DROP INDEX IF EXISTS sessions_expiry_idx ON sessions;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS shopItems;

DROP TABLE IF EXISTS shopItemsOwned;

DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TABLE IF EXISTS reports;

DROP TABLE IF EXISTS admins;

