DROP TABLE IF EXISTS user_stats;

DROP TABLE IF EXISTS user_achievements;

DROP TABLE IF EXISTS sessions;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS shopItems;

DROP TABLE IF EXISTS shopItemsOwned;

DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TABLE IF EXISTS reports;

DROP TABLE IF EXISTS admins;

DROP TABLE IF EXISTS timer;

DROP TABLE IF EXISTS todo;

